# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZiPingSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZiPingSwift
   pod 'Alamofire', '~> 4.4.0'
   pod 'Kingfisher', '~> 3.6.1'
   pod 'SnapKit', '~> 3.2.0'
   pod 'HandyJSON', '~> 4.1.1'
   pod 'MJRefresh', '~> 3.1.15'
   pod 'SwiftyJSON', '~> 3.1.4'
   pod 'IQKeyboardManagerSwift', '~> 5.0.6'
   pod 'DZNEmptyDataSet', '~> 1.8.1'
   pod 'SideMenu', '~> 2.3.3'
   pod 'ESTabBarController-swift', '~> 2.5'
   pod 'SwiftTheme', '~> 0.4.0'
   pod 'Charts', '<= 3.0.2'
   pod 'JPush', '~> 3.0.6'

  target 'ZiPingSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZiPingSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
